# Generated by Django 3.1.4 on 2021-01-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20210116_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
