# Generated by Django 3.1.4 on 2021-01-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_auto_20210116_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address1',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес по прописке'),
        ),
        migrations.AddField(
            model_name='person',
            name='address2',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Адрес проживания'),
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Краткая характеристика'),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone1',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone2',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Телефон'),
        ),
    ]
