# Generated by Django 3.1.4 on 2021-01-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_customer_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
