# Generated by Django 3.1.5 on 2021-01-17 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_auto_20210116_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1, verbose_name='Пол'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('task_status', models.CharField(choices=[('A', 'В планах'), ('B', 'В работе'), ('C', 'Выполнена')], default='A', max_length=1, verbose_name='Статус')),
                ('dead_line', models.DateField(blank=True, null=True, verbose_name='Исполнить до')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='baseapp.customer', verbose_name='Заказчик')),
                ('from_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_customer', to='baseapp.employee', verbose_name='От заказчика')),
                ('from_performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_performer', to='baseapp.employee', verbose_name='От исполнителя')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performer', to='baseapp.customer', verbose_name='Исполнитель')),
            ],
        ),
    ]
