# Generated by Django 3.1.4 on 2021-01-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_auto_20210117_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Заказчик', 'verbose_name_plural': 'Заказчики'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник заказчика', 'verbose_name_plural': 'Сотрудники заказчика'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Физическое лицо', 'verbose_name_plural': 'Физические лица'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('A', 'Запланирована'), ('B', 'Выполняется'), ('C', 'Проверяется'), ('D', 'Выполнена')], default='A', max_length=1, verbose_name='Статус'),
        ),
    ]
